<?php
	include('./requiert/new-form/header.php');
	$meta_title = 'cashbackreduction.com : Mentions légales';
	$meta_description = '';
?> 
   
      
 <div class='cashback_view'>
    <div class='height-30-wave'>
    <h1 class="text-center text-white  title_h1">
      Politique de cookies
    </h1>
    </div>
</div>
            <div class="row container-top">
         <div class="container">
            <div class="row">
               <div class="col-md-8 mx-auto">
                  <div class="bg-white p-5">
    <div class='row'> 
        <h3 class="h5 text-primary">Les cookies</h3>
        <h3 class="h5 text-primary">Qu'entend-on par cookies ?</h3>
            <p>
            Nous désignons principalement par “cookies” les petits fichiers qui sont déposés sur votre  terminal  (ordinateur, mobile, smartphone, tablette…)  lorsque vous naviguez sur le service iGraal. Par extension, nous désignons par “cookies” d'autres technologies ayant un comportement similaire et assurant la collecte d'informations relatives à votre navigation et à vos interactions avec iGraal, sous réserve des choix que vous avez exprimés. Nous utilisons ces technologies pour différentes raisons, notamment pour faciliter votre navigation, protéger nos services d'attaques informatiques, pour réaliser des mesures d'audience, pour vous proposer des coupons de réduction susceptibles de vous intéresser ou encore pour vous proposer des fonctionnalités issues de service tiers comme l'inscription et la connexion en 1 clic depuis vos réseaux sociaux favoris.
            </p>
            <br/>
            <p>Les cookies ne permettent pas de vous identifier personnellement mais ils enregistrent des informations relativent à votre navigation et à votre comportement sur iGraal. Nous pouvons ensuite y accéder lors de vos navigations ultérieures. Prenons un exemple : vous avez choisi d'installer l'extension iGraal sur votre navigateur, nous allons stocker cette information dans un cookie pour ne plus vous présenter de bannière de téléchargement de l'extension lorsque vous venez sur iGraal et ne plus vous déranger avec cette information. Plutôt utile, non ?</p>
            <br/>
            <p>Notez que les informations collectées par ces cookies peuvent être exploitées par nous-même ou par un partenaire (une société tierce). Lorsque c'est le cas, nous précisons le nom du partenaire dans la liste des cookies ci-dessous.</p>
            <br/>
    </div>  

    <div class='row'> 
        <h3 class="h5 text-primary">Quels sont mes choix concernant les cookies ?</h3>
        <h2 class="h5 text-info">Accord pour le dépôt de cookies</h2>
        <p>Pour tous les cookies non essentiels, nous vous demanderons votre accord avant de les déposer sur votre terminal. Pour cela un bandeau d'information s'affiche lorsque vous naviguez sur iGraal pour vous informer de leur présence et vous permettre, le cas échéant, de vous opposer à leur dépôt sur votre terminal. Vous pouvez choisir d'accepter ou de refuser tous les cookies, tous les cookies d'une catégorie ou un cookie bien précis. Bref, vous avez le choix !</p>
        <h2 class="h5 text-info">Sur les sites iGraal</h2>
        <p>Nous vous offrons la possibilité de modifier le paramétrage de vos cookies directement depuis notre site. Un lien “Gérer mes cookies” est présent en bas de chacune des pages.</p>
        <br/>
        <h2 class="h5 text-info">Sur les applications mobiles iGraal</h2>
        <p>Vous pouvez gérer le paramétrage de vos cookies directement depuis votre application iGraal dans la section ”informations > Préférences Cookie”.  Dans tous les cas, si vous désinstallez l'application, les cookies disparaîtront.</p>
        <h2 class="h5 text-info">Sur l'extension navigateur iGraal</h2>
        <p>Vous pouvez gérer le paramétrage de vos cookies directement depuis votre extension iGraal dans la section ”Confidentialité et Cookies”.  Dans tous les cas, si vous désinstallez l'extension, les cookies disparaîtront.</p>
        <h2 class="h5 text-info">Depuis votre navigateur</h2>
        <p>Vous pouvez également configurer votre navigateur pour gérer vos préférences de cookie. Chaque navigateur propose des réglages différents. Nous vous indiquons pour référence, quelques pages d'aide sur les sites des éditeurs les plus courants : </p>
        <p>Internet Explorer™ 11 : https://support.microsoft.com/fr-fr/help/17442/windows-internet-explorer-delete-manage-cookies<br/>
            Chrome™ : http://support.google.com/chrome/bin/answer.py?hl=fr&hlrm=en&answer=95647<br/>
            Edge : https://support.microsoft.com/fr-fr/help/4468242/microsoft-edge-browsing-data-and-privacy<br/>
            Safari™ : http://support.apple.com/kb/PH5042<br/>
            Firefox™ : http://support.mozilla.org/fr/kb/activer-desactiver-cookies</p>
    </div>  

    <div class='row'> 
        <h3 class="h5 text-primary">Quels cookies sont utilisés par iGraal ?</h3>
        <p>Nous utilisons 4 types de cookie pour différents besoins (ou “finalités”).</p><br/>
        <h2 class="h5 text-info"> Les cookies dit “Essentiels”</h2><br/>
        <p>Ces cookies nous permettent de suivre les performances de nos services et de détecter des problèmes de navigation ou de sécurité afin de réduire autant que possible la gêne occasionnée pour nos utilisateurs. Ils sont également utilisés pour vous rendre le service de cashback iGraal comme par exemple vous permettre de vous connecter ou encore identifier vos achats chez nos partenaires marchands. Ces cookies essentiels servent également à mémoriser vos préférences de navigation et vos préférences en matière de cookie. Ces cookies ne contiennent et ne sont associées à aucune information nominative.
        </p>
        <h2 class="h5 text-info">Les cookies de Mesure d'Audience</h2>
        <p>Ces cookies nous permettent de produire des statistiques globales et agrégées relatives à la fréquentation de notre service (ex : nombre de visites, pages et rubriques  consultées, temps passé sur le service, région de connexion, type d'appareil utilisé, provenance d'un visiteur...). Ces cookies permettent d'améliorer les performances, les fonctionnalités et les services qui vous sont proposés ainsi que d'améliorer et d'optimiser nos campagnes de communication pour attirer de nouveaux membres dans la communauté :)</p>
        <h2 class="h5 text-info"> Les cookies de Fonctionnalité Tierces</h2>
        <p>Ces cookies nous permettent, ou permettent à nos partenaires tiers, de vous offrir certaines fonctionnalités sur notre service. C'est par exemple le cas des boutons d'inscription et de connexion automatique via Facebook, Google ou Apple. Ou encore les boutons de partage sur les réseaux sociaux. Ces cookies peuvent être déposés sur nos services par les réseaux sociaux du fait de l'intégration de leurs applications à nos services. Le réseau social fournissant une de ces applications est susceptible de vous identifier grâce à ses boutons et à ses propres cookies, même si vous ne les avez pas utilisés lors de votre consultation de nos services.
        </p>
        <br/>
        <p>Certains de nos partenaires sont susceptibles de combiner les données collectées via les cookies qu'ils exploitent sur nos services avec d'autres informations que vous leur avez fournies ou qu'ils ont collectées lors de votre utilisation de leurs propres services.<br/>
    </div>  

    <div class='row'> 
        <h3 class="h5 text-primary"> Les cookies de Coupons Personnalisés</h3>
        <p>Ces cookies nous permettent, ou permettent à nos partenaires tiers, de suivre et piloter votre exposition et vos interactions avec les contenus présents sur nos services, mais également sur d'autres services sur lesquels ils déposent des cookies, notamment pour vous proposer des coupons de réduction personnalisés. Ils permettent d'identifier quelles informations pourraient vous intéresser le plus afin de vous proposer des coupons de réduction personnalisés adaptés à vos centres d'intérêts.</p><br/>
        <p>Certains de nos partenaires sont susceptibles de combiner les données collectées via les cookies qu'ils exploitent sur nos services avec d'autres informations que vous leur avez fournies ou qu'ils ont collectées lors de votre utilisation de leurs propres services.</p>
    </div> 
    </div> 
    </div> 
    </div> 
    </div> 
    </div> 
	 
		
<?php
	include('./requiert/new-form/footer.php');
?>